language: java
jdk:
- openjdk8
sudo: required
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAZOKKB636GOXML5BE
  secret_access_key:
    secure: "Tk2pQCyST251h+N9OBHkL2oOzYFZKt5gGX6MtGYjxEEDj10r5UtOrmPQ59629qfGLMjjUG3Ag3WLTyWSTQ0kgh0ybj5pBS2ITqXh8FwMpYpT+8LzM+wujl1rHJkNGU9wYnnQMLZ16GpyxZKyY+JZMJhh/bM0+FUkQCcjBBZKXxJuU8kNjwc7DVUhUiBo5v4J/WinKiKQb3UNlZBmJYxuQbZQpzDjQ0FvmPS6jUVwx855rYXPqlyGYIPhQJ8Zg2a39/5ceUoIyi6O69GQnKVTMkoHKOy8SSaNAPTNy+Mszo1mU7jObJchhqwm3bU0g5WEzttpHet9HTxuo+2Rk6D/onTfsKoI5p5+Sr5S46M+BwsKwEYos1dIB+F8zNOKAXaxeXGX9pnXvhg/+mVvyvijEsYgnFVyE7Fepo7/Tv54KSaDZSh3k06aIix4UtZETFukOLi/S8R9htL6fznn4LuygUJgz8OerqVsICIODEwIuGhL5epeAHok8tWPDDfrVjYQt3vEdO6SEISnpljZUrkEc65Z46IGiSaFmhTV+rjnyxwNs4w/+nd/+GEWAwlL0+YUwZgS3VLtENX0wHqwQMsXiKb9MXZGVochRj5aAOVBOIf3ehEeKPt1yQyKroCOEYbzfX9om14gX4paSeSlXas0kv2b8/jYqqi/fE1jb1aN8PY="
  region: us-east-1
  app: BridgeServer2-application
  env: bridgeserver2-$TRAVIS_BRANCH
  bucket_name: org-sagebridge-bridgeserver2-deployment-$TRAVIS_BRANCH
  zip-file: target/BridgeServer2-2.0.war
  on:
    all_branches: true
