language: java
jdk:
- oraclejdk8
sudo: required
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAJ6YWVFOX3GHDXVRQ
  secret_access_key:
    secure: "GoSp36xApE3ivXojJ5hisot6Q3KMd8RHp36a/lEUuBEqXrmmvYFSk58KyxE2WOkbCfscRGTnIclny8dOWfvoJ33utZwsQSXuKf8H3i0S2EErWvce/FqBOg/0gZLsxAMUvL1+OiU00dgf45CG1JmL3fFRlWXjEY23UfpX+4zy6qDN5blJtALxiIXOZA/zNVLuhWXVoZeGpn9S/OcV7tWt/9bo0Uaytq6wX90cAgb9n+vgjgqDV5/j2tm72Ij77foSLXTfgpJqDR0G1fe697nN3jApceuXc4lNYhsH3LW9IMGBQ6EMroBr8PhRU7ATIOFHmK0AV9wyDwE+q20Ai0AzGzWTi+wtU/KYTfbZpETxremuATNd7O87+Mwn+akLFVxfQbRYdEA8gxjr33GVgE8ES1j0YP0mLPQHqBl4INIZrvRcSgOHro5T+EGnP5xTZYKwhLWdC55luicaG+ih5W19kgQawg/4cI9SXo03y39DDPSLxqlI8UuJYn4HE1bNtOg4lYp0mk9ydnJwE+IhPvITpNmjqCKNia4Bskznj+ws0t+nInK1A/zYPsvk6faBLtWzM6BiO8UcD8SN4VQw0P3tl97Q+uAFpK+sxtBMFcPh5HfuDukqdoujjjm5Wn8TSB0NZ0qjoZtWQ7MwydGYOiSqa0xZKeMR+/obDIWF0x26zn0="
  region: us-east-1
  app: BridgeServer2-application
  env: bridgeserver2-$TRAVIS_BRANCH
  bucket_name: org-sagebridge-bridgeserver2-deployment-$TRAVIS_BRANCH
  zip-file: target/BridgeServer2-2.0.war
  on:
    all_branches: true
